image:
  name: pulumi/pulumi-python:latest
  entrypoint: [""]

stages:
  - validate
  - install
  - preview
  - refresh
  - dev

cache:
  paths:
    - .pulumi
    - "**/__pycache__/"
    - .venv/

variables:
  GIT_DEPTH: "1"
  GIT_STRATEGY: clone
  AWS_REGION: "us-east-2"
  PULUMI_BACKEND_URL: "s3://${PULUMI_S3_BUCKET}"
  STACK_NAME: "dev"

before_script:
  - echo "Setting up environment variables"
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_REGION}
  - pulumi login ${PULUMI_BACKEND_URL}

validate:
  stage: validate
  script:
    - test -f requirements.txt || (echo "Missing requirements.txt" && exit 1)
    - test -f Pulumi.yaml || (echo "Missing Pulumi.yaml" && exit 1)
    - test -f __main__.py || (echo "Missing __main__.py" && exit 1)
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

install:
  stage: install
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv/
      - .pulumi/
    expire_in: 1 week
  needs:
    - job: validate
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

preview:
  stage: preview
  script:
    - source .venv/bin/activate
    - pulumi stack select ${STACK_NAME} || pulumi stack init ${STACK_NAME}
    - pulumi preview --stack ${STACK_NAME} --diff --non-interactive --color always
  needs:
    - install
  only:
    - branches
  when: on_success
  dependencies:
    - install

refresh:
  stage: refresh
  script:
    - source .venv/bin/activate
    - pulumi refresh --yes --non-interactive --color always --skip-preview --stack ${STACK_NAME} 
  needs:
    - install
  when: manual
  only:
    - branches
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

deploy-to-dev:
  stage: dev
  script:
    - source .venv/bin/activate
    - pulumi up --yes --non-interactive --color always --skip-preview --stack ${STACK_NAME}
  needs:
    - job: preview
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  when: manual

destroy-dev:
  stage: dev
  script:
    - source .venv/bin/activate
    - pulumi destroy --yes --non-interactive --color always --stack ${STACK_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  when: manual